iSach/UltraCosmetics

src/main/java/be/isach/ultracosmetics/Core.java
src/main/java/be/isach/ultracosmetics/cosmetics/gadgets/GadgetColorBomb.java

Use Collections.synchronizedList instead of arrayList or list in Core class.
Fix color bomb affects Citizen NPC.

two modifcations

---

src/main/java/be/isach/ultracosmetics/listeners/PlayerListener.java

Stops plugin conflicting with worlds that do not use cosmetics.

Updates InventoryClickEvent to check world

---

src/main/java/be/isach/ultracosmetics/config/MessageManager.java
src/main/java/be/isach/ultracosmetics/cosmetics/mounts/MountFlyingBoat.java
src/main/java/be/isach/ultracosmetics/cosmetics/mounts/MountFlyingShip.java
src/main/java/be/isach/ultracosmetics/cosmetics/mounts/MountType.java
src/main/java/be/isach/ultracosmetics/cosmetics/treasurechests/TreasureChest.java
src/main/java/be/isach/ultracosmetics/manager/GadgetManager.java

1. Copy your work and mess them into one mount "flying boat", I cannot think any good english name for it . You may change it to something much more interesting.
- it's a boat could flying around like EnderDragon
- Right click or left click will spawn an TNT , when the TNT reaches the ground, it will explode. Cooldown 10 seconds without any message or actionbar notification (not like gadgets).
- Uhm... What's more ?
2. Fix TreasureChest class's import stuff.
Cheers!

A mount and a few fixes

---

core/src/main/java/be/isach/ultracosmetics/config/MessageManager.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/pets/PetMooshroom.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/pets/PetType.java
core/src/main/java/be/isach/ultracosmetics/run/FallDamageManager.java
core/src/main/java/be/isach/ultracosmetics/version/IPets.java
core/src/main/resources/plugin.yml
v1_10_R1/src/main/java/be/isach/ultracosmetics/v1_10_R1/Pets.java
v1_10_R1/src/main/java/be/isach/ultracosmetics/v1_10_R1/customentities/CompanionCube.java
v1_10_R1/src/main/java/be/isach/ultracosmetics/v1_10_R1/customentities/CustomEntities.java
v1_10_R1/src/main/java/be/isach/ultracosmetics/v1_10_R1/pets/CustomEntityPet.java
v1_10_R1/src/main/java/be/isach/ultracosmetics/v1_10_R1/pets/PetCompanionCube.java
v1_8_R3/src/main/java/be/isach/ultracosmetics/v1_8_R3/Pets.java
v1_8_R3/src/main/java/be/isach/ultracosmetics/v1_8_R3/customentities/CompanionCube.java
v1_8_R3/src/main/java/be/isach/ultracosmetics/v1_8_R3/customentities/CustomEntities.java
v1_8_R3/src/main/java/be/isach/ultracosmetics/v1_8_R3/pets/CustomEntityPet.java
v1_8_R3/src/main/java/be/isach/ultracosmetics/v1_8_R3/pets/PetCompanionCube.java
v1_9_R1/src/main/java/be/isach/ultracosmetics/v1_9_R1/Pets.java
v1_9_R1/src/main/java/be/isach/ultracosmetics/v1_9_R1/customentities/CompanionCube.java
v1_9_R1/src/main/java/be/isach/ultracosmetics/v1_9_R1/customentities/CustomEntities.java
v1_9_R1/src/main/java/be/isach/ultracosmetics/v1_9_R1/pets/CustomEntityPet.java
v1_9_R1/src/main/java/be/isach/ultracosmetics/v1_9_R1/pets/PetCompanionCube.java
v1_9_R2/src/main/java/be/isach/ultracosmetics/v1_9_R2/Pets.java
v1_9_R2/src/main/java/be/isach/ultracosmetics/v1_9_R2/customentities/CompanionCube.java
v1_9_R2/src/main/java/be/isach/ultracosmetics/v1_9_R2/customentities/CustomEntities.java
v1_9_R2/src/main/java/be/isach/ultracosmetics/v1_9_R2/pets/CustomEntityPet.java
v1_9_R2/src/main/java/be/isach/ultracosmetics/v1_9_R2/pets/PetCompanionCube.java

Not much to it, just added two pets and related messages and configs.

Add Mooshroom and companion cube Pets

---

core/build.gradle
core/src/main/resources/plugin.yml

Just change the version in build.gradle

Automagically replace version in plugin.yml

---

core/src/main/java/be/isach/ultracosmetics/config/MessageManager.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/emotes/EmoteType.java

Add Wink Emote

---

core/src/main/java/be/isach/ultracosmetics/UltraCosmetics.java
core/src/main/java/be/isach/ultracosmetics/config/MessageManager.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/gadgets/GadgetPortalGun.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/mounts/Mount.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/suits/Suit.java
core/src/main/java/be/isach/ultracosmetics/listeners/PlayerListener.java
core/src/main/java/be/isach/ultracosmetics/menu/CosmeticMenu.java

Added an option to disable certain commands (e.g. `/hat`) while holding a cosmetic.

Added a disabled commands option & fixed issues

---

core/src/main/java/be/isach/ultracosmetics/config/MessageManager.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/Cosmetic.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/gadgets/GadgetAntiGravity.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/gadgets/GadgetDiscoBall.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/suits/Suit.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/type/SuitType.java
core/src/main/java/be/isach/ultracosmetics/listeners/PlayerListener.java
core/src/main/java/be/isach/ultracosmetics/menu/menus/MenuSuits.java
core/src/main/java/be/isach/ultracosmetics/player/UltraPlayer.java

Fixed single suit permissions and some errors people were having.

Fixed single suit permissions & other issues

---

core/src/main/java/be/isach/ultracosmetics/cosmetics/gadgets/Gadget.java
core/src/main/java/be/isach/ultracosmetics/menu/CosmeticMenu.java
core/src/main/java/be/isach/ultracosmetics/menu/Menu.java
core/src/main/java/be/isach/ultracosmetics/menu/menus/MenuPets.java
core/src/main/java/be/isach/ultracosmetics/menu/menus/MenuSuits.java
core/src/main/java/be/isach/ultracosmetics/player/UltraPlayer.java
core/src/main/java/be/isach/ultracosmetics/util/ItemFactory.java

Fixed the fill with blank slots feature and started working on pet renaming.

Fix and pet rename WIP

---

core/src/main/java/be/isach/ultracosmetics/command/subcommands/SubCommandToggle.java

Syntax to toggle suits: `/uc toggle suit <suit type:suit piece> <player>`.

Added /uc toggle support for suits

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

- Added code of conduct
- Added contributing guidelines
- Added issue template
- Added pull request template

Community standards update

---

core/src/main/java/be/isach/ultracosmetics/cosmetics/gadgets/GadgetParachute.java

The purpose of this pull request is to fix issue #362.
The changes I've made fix issue #362 by accounting for non-solid blocks.

Fixed #362

---

v1_12_R1/src/main/java/be/isach/ultracosmetics/v1_12_R1/AnvilGUI.java

Mojang changed distance check for anvils
Update the NMS source for AnvilGUI, using a new field, checkReachable

Fix AnvilGUI on 1.12.X

---

settings.gradle
v1_13_R1/build.gradle
v1_13_R2/build.gradle

The purpose of this pull request is to add 1.13 R1 and 1.13 R2 to Gradle.
My changes add 1.13 R1 and 1.13 R2 to Gradle.

Add 1.13 R1 and 1.13 R2 to Gradle

---

build.gradle
core/build.gradle
v1_10_R1/build.gradle
v1_11_R1/build.gradle
v1_12_R1/build.gradle
v1_13_R1/build.gradle
v1_13_R2/build.gradle
v1_14_R1/build.gradle
v1_8_R1/build.gradle
v1_8_R2/build.gradle
v1_8_R3/build.gradle
v1_9_R1/build.gradle
v1_9_R2/build.gradle

To fix Gradle building.
Added alternate repos so dependencies resolve correctly.

Fixed Gradle build

---

core/src/main/java/be/isach/ultracosmetics/UltraCosmetics.java
core/src/main/java/be/isach/ultracosmetics/treasurechests/TreasureChest.java
core/src/main/java/be/isach/ultracosmetics/util/BlockUtils.java
core/src/main/java/be/isach/ultracosmetics/util/GeneralUtil.java

Fixed that the BlockStates after opening a TreasureChest wouldn't return to normal the saved state in 1.12.2.

BlockState Fix

---

core/src/main/java/be/isach/ultracosmetics/UltraCosmetics.java
core/src/main/java/be/isach/ultracosmetics/UltraCosmeticsData.java
core/src/main/java/be/isach/ultracosmetics/command/subcommands/SubCommandTreasure.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/pets/PetSnowman.java
core/src/main/java/be/isach/ultracosmetics/listeners/MainListener.java

1. Fixes snowmen leaving trails as noted in https://github.com/iSach/UltraCosmetics/pull/552#issuecomment-1001696478
2. Misc fixes
1. Add listener to prevent snow trails if snowman has UC metadata.
2. Misc fixes
Parenthesis correspond to purpose list

Prevent snowman trails; misc fixes

---

LICENSE
README.md

Changes the license of the project, addressing issue #569.
I don't believe I can change the license myself as I am not the author, so I'm opening a PR.
Replaces the old license with GNU Affero v3.
I considered GPL v3 and Affero. It seems the main difference is Affero considers network use (i.e. on a server) as redistribution while GPL does not, so I thought Affero would be a better fit. But again, I am not the author, this is just a guess.

Change license to GNU Affero

---

core/src/main/java/be/isach/ultracosmetics/cosmetics/pets/PetPiglin.java
core/src/main/java/be/isach/ultracosmetics/cosmetics/type/PetType.java

Fix Piglin Pet Zombification
Adds `setImmuneToZombification` to the piglin pet

Fix Piglin Pet Zombification

---

README.md

Update/Improve UC description and add up-to-date version counter
If you want to see the difference (how it looks):
The updated version: https://github.com/Chris6ix/UltraCosmetics/blob/master/README.md
The current version: https://github.com/iSach/UltraCosmetics/blob/master/README.md
Updating/Improving the UC description and adding up-to-date version counter?
/

Update UC Readme
